import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const testVaultPluginDir = "/Users/s-ikari/work/playground/ainotebook-test-vault/.obsidian/plugins/obsidian-ai-notebook";

function copyToTestVault() {
	try {
		if (fs.existsSync(testVaultPluginDir)) {
			fs.copyFileSync("main.js", path.join(testVaultPluginDir, "main.js"));
			fs.copyFileSync("manifest.json", path.join(testVaultPluginDir, "manifest.json"));
			if (fs.existsSync("styles.css")) {
				fs.copyFileSync("styles.css", path.join(testVaultPluginDir, "styles.css"));
			}
			console.log(`[Build] Plugin files automatically synced to: ${testVaultPluginDir}`);
		}
	} catch (e) {
		console.warn("[Build] Warning: Failed to sync to test vault:", e);
	}
}

const copyPlugin = {
	name: "copy-plugin",
	setup(build) {
		build.onEnd(result => {
			if (result.errors.length === 0) {
				copyToTestVault();
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyPlugin]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
